---
title: "mcseq"
author: "Kushagra Gupta"
date: "7/19/2021"
output: html_document
---

```{r, results=FALSE, warning=FALSE, message=FALSE}
set.seed(10)
library(mcmcse)
library(Rcpp)
library(rbenchmark)
sourceCpp('../mcseqbm.cpp')
sourceCpp('../mcseqobm.cpp')
sourceCpp('../mcseqsub.cpp')
source('batchSize_final.R')
```

```{r}
quant = function(input, q) { quantile(input, prob = q, type = 1, names = FALSE) }

mcseq_new <- function(x, q, size = NULL, g = NULL, method = c("bm", "obm", "sub"), warn = FALSE) {
  
  if(is.function(g))
    x = sapply(x, g)
  
  n = length(x)
  
  if (n < 1000)
  {
      if (warn)
          warning("too few samples (less than 1,000)")
      if (n < 10)
          return(NA)
  }
  
  if(is.null(size)) {
    b <- batchSize_final(x = x, method = method, g = g)
  } else if(size == "sqroot")  {
    b <- floor(sqrt(n))
  } else if(size == "cuberoot") {
    b <- floor(n^(1/3))
  } else  {
    if (!is.numeric(size) || size < 1 || size >= n || floor(n/size) <=1) {
      warning("size is either too large, too small, or not a number. Setting 'size' to n^(1/2)")
      size = sqrt(n)
    }
        
    b <- floor(size)
  }
  
  a <- floor(n/b)
  
  method = match.arg(method)
  
  if (! is.numeric(q) || q <= 0 || q >= 1)    {
        stop("'q' must be from (0, 1)")
  }
  
  xi.hat = quant(x, q)
  
  if(method == "bm")  {
    var.hat = mcseqbm(x, b, xi.hat)
    f.hat.junk = density(x, from = xi.hat, to = xi.hat, n = 1)
    f.hat = f.hat.junk$y
    se = sqrt(var.hat / n) / f.hat
  } else if(method == "obm")  {
    var.hat = mcseqobm(x, b, xi.hat)
    f.hat.junk = density(x, from = xi.hat, to = xi.hat, n = 1)
    f.hat = f.hat.junk$y
    se = sqrt(var.hat / n) / f.hat
  } else  {
    var.hat = mcseqsub(x, b, q, quant)
    se = sqrt(var.hat / n)
    
  }
  
  
  list(est = xi.hat, se = se) 
}


```

```{r, cache = TRUE}
n = 1e6
x = double(n)
rho = 0.99
x[1] = 2
for (i in 1:(n - 1))
    x[i + 1] = rho * x[i] + rnorm(1)
```

```{r, cache = TRUE}
print("bm estimators")
print(mcse.q(x, q = 0.4, size = "sqroot", method = "bm"))
print(mcseq_new(x, q = 0.4, size = "sqroot", method = "bm"))

print("obm estimators")
print(mcse.q(x, q = 0.4, size = "sqroot", method = "obm"))
print(mcseq_new(x, q = 0.4, size = "sqroot", method = "obm"))

print("sub estimators")
print(mcse.q(x, q = 0.4, size = "sqroot", method = "sub"))
print(mcseq_new(x, q = 0.4, size = "sqroot", method = "sub"))
```


```{r, cache = TRUE}
benchmark(replications = 1e2, mcse.q(x, q = 0.4, size = "sqroot", method = "bm"), mcseq_new(x, q = 0.4, size = "sqroot", method = "bm"))
```

```{r, cache=TRUE}
benchmark(replications = 1e2, mcse.q(x, q = 0.4, size = "sqroot", method = "obm"), mcseq_new(x, q = 0.4, size = "sqroot", method = "obm"))
```

```{r, cache = TRUE}
benchmark(replications = 1e2, mcse.q(x, q = 0.4, size = "sqroot", method = "sub"), mcseq_new(x, q = 0.4, size = "sqroot", method = "sub"))
```


