// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace arma;
using namespace Rcpp;

// inseq
List inseq(mat M, bool adjust);
RcppExport SEXP _mcmcse_inseq(SEXP MSEXP, SEXP adjustSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< mat >::type M(MSEXP);
    Rcpp::traits::input_parameter< bool >::type adjust(adjustSEXP);
    rcpp_result_gen = Rcpp::wrap(inseq(M, adjust));
    return rcpp_result_gen;
END_RCPP
}
// mbmC
mat mbmC(const arma::mat& chain, double b);
RcppExport SEXP _mcmcse_mbmC(SEXP chainSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type chain(chainSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(mbmC(chain, b));
    return rcpp_result_gen;
END_RCPP
}
// mobmC
mat mobmC(const arma::mat& chain, double b);
RcppExport SEXP _mcmcse_mobmC(SEXP chainSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type chain(chainSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(mobmC(chain, b));
    return rcpp_result_gen;
END_RCPP
}
// msveC
mat msveC(const arma::mat& chain, double b, String method);
RcppExport SEXP _mcmcse_msveC(SEXP chainSEXP, SEXP bSEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type chain(chainSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< String >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(msveC(chain, b, method));
    return rcpp_result_gen;
END_RCPP
}
