# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

inseq <- function(M, adjust = TRUE) {
    .Call('_mcmcse_inseq', M, adjust)
}

mbmC <- function(chain, b) {
    .Call(`_mcmcse_mbmC`, chain, b)
}

mobmC <- function(chain, b) {
    .Call(`_mcmcse_mobmC`, chain, b)
}

msveC <- function(chain, b, method = "bartlett") {
    .Call(`_mcmcse_msveC`, chain, b, method)
}

