# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

eureka <- function(order_max, r, g, coefs, var, a, threshold) {
    .Call(`_mcmcse_eureka`, order_max, r, g, coefs, var, a, threshold)
}

batchsize_cpp <- function(n, p, xacf_mat, max_order, method, threshold = 0.01) {
    .Call(`_mcmcse_batchsize_cpp`, n, p, xacf_mat, max_order, method, threshold)
}

inseq <- function(M, adjust = TRUE) {
    .Call(`_mcmcse_inseq`, M, adjust)
}

lag <- function(s, n, b, method) {
    .Call(`_mcmcse_lag`, s, n, b, method)
}

mbmC <- function(chain, b) {
    .Call(`_mcmcse_mbmC`, chain, b)
}

mcseqbm <- function(x, b, xi_hat) {
    .Call(`_mcmcse_mcseqbm`, x, b, xi_hat)
}

mcseqobm <- function(x, b, xi_hat) {
    .Call(`_mcmcse_mcseqobm`, x, b, xi_hat)
}

mcseqsub <- function(x, b, q, f) {
    .Call(`_mcmcse_mcseqsub`, x, b, q, f)
}

mobmC <- function(chain, b) {
    .Call(`_mcmcse_mobmC`, chain, b)
}

msveC <- function(chain, b, method = "bartlett") {
    .Call(`_mcmcse_msveC`, chain, b, method)
}

